### ISSUE TITLE
Support Windows

### ISSUE THREAD

**Issue by AmitMY** [mreq/xelatex-emoji#13]
Using the file found in the `README`:
```latex
\documentclass{article}

\usepackage{xltxtra}
\usepackage{xelatexemoji}

\setmainfont{Ubuntu}

\begin{document}

    Hello, 🌎. Lorem 😃 😄 😅 😆 ipsum dolor.

\end{document}
```
I get the error, on windows:
> miktex-maketfm: major issue: So far, no MiKTeX administrator has checked for updates.
> ! Package fontspec Error: The font "Ubuntu" cannot be found.

**Comment by mreq** [comment]
Use a different font then. The file in README is just an example
