### ISSUE TITLE
Detailed installation instructions

### ISSUE THREAD

**Issue by wladston** [mreq/xelatex-emoji#2]
I didn't know about the texmf folder, so it took me some long minutes to figure out how to install it. I propose adding the following to the installation instructions:

```
mkdir -p ~/Library/texmf/tex/latex/local && ~/Library/texmf/tex/latex/local
git clone git@github.com:mreq/xelatex-emoji.git
texhash xelatex-emoji
```

**Comment by mreq** [comment]
Added a link. Thanks.
